name: overdriveapp
description: Overdrive app for Google IO Extended Tegucigalpa.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-147.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_sound: 9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/cleanGuitar.wav

